name: Pull Request Checks
run-name: Pull Request Checks
on: pull_request

jobs:
  validate_lib:
    name: Validate Library
    uses: ./.github/workflows/validate-project-template.yml
    with:
      NODE_VERSION: '20'
    secrets:
      CDK_AWS_ACCESS_KEY_ID: ${{ secrets.CDK_AWS_ACCESS_KEY_ID }}
      CDK_AWS_SECRET_ACCESS_KEY: ${{ secrets.CDK_AWS_SECRET_ACCESS_KEY }}

  integration_tests:
    name: Integration Tests
    needs: validate_lib
    uses: ./.github/workflows/integration-tests-check.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.CDK_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CDK_AWS_SECRET_ACCESS_KEY }}