name: Validate Project Workflow
run-name: Validate Project Workflow
on:
  workflow_call:
    inputs:
      NODE_VERSION:
        type: string
        required: false
        default: '22'
    secrets:
      CDK_AWS_ACCESS_KEY_ID:
        required: true
      CDK_AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  validate_project:
    name: Validate Library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CDK_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CDK_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup
        run: |
          npm i -g zx
          zx ./scripts/setup.mjs

      - name: Lint
        run: npm run lint
        
      - name: Test Lib
        run: |
          npm run test

      - name: Build Lib
        run: |
          npm run build